### PR TITLE
Eliminate runtime dependency on junit

### PR DESCRIPTION
**Pull request by timboudreau**
This patch eliminates `kivakit-core` and several other projects' direct, non-test dependency on junit,
which causes dependees to inherit that dependency.

Doing so requires that we

  * Move `CoreUnitTest` and friends out of `kivakit-core` into a new `kivakit-test-support` project
  * Do the same for `UnitTest` in `kivakit-resource` --> `kivakit-resource-test-support`
  * Move tests for those two projects into their own separate tests-only projects, so attempting to
    use the test-support classes does not create a cyclic dependency (this is a Maven limitation)
    * There are new `kivakit-core-tests` and `kivakit-resource-tests` project for those tests

I've used an at least somewhat familiar naming convention of `*-test-support` for _projects containing
classes that help write tests_ and `*-tests` for _tests of some project_ (think `PropertyChangeSupport`)
to keep the purpose of the projects unambiguous.

Note:  I was not sure what to do for `README.md` files in the new projects - the ones in other projects appear machine-generated - ?

### Issue Ticket
[Include a ticket link from [KivaKit Issues](https://github.com/Telenav/kivakit/issues)]

### Description
[Describe the contribution]

### CODE REVIEW

**Comment by timboudreau** [comment]
Okay, so maybe rename things so `kivakit-test-support` is the thing that contains `UnitTest`, and the project with the parent classes (`CoreUnitTest` and friends) gets renamed `kivakit-core-test-support` or something like that?

I don't feel strongly about "-support" as a suffix, but it is important for anyone new to the codebase that it's consistent - i.e. if you see a package named "-tests" you _know_ either that it's classes-that-help-you-write-tests, or that it's unit-tests-of-some-other-package and don't have to look to find out.

That could also be done by using "-unittests" for projects that are just tests of another thing, and reserve "-tests" for things that support writing tests, if "-support" seems clunky.

**Comment by jonathanl-telenav** [comment]
support does seem clunky. what about hiding some of this stuff better. the only thing end users really have any business with is the kivakit.test module. the rest could be buried in a module hierarchy that highlights kivakit.test and hides the rest:

kivakit
    kivakit-test (kivakit.test)     
    kivakit-internal
            test (kivakit-internal-test, kivakit.internal.test... containing what is now in kivakit.core.test)
            unit-tests
                core (kivakit-internal-unit-tests-core, kivakit.internal.unit.tests.core)
                resources (kivakit-internal-unit-tests-resources, kivakit.internal.unit.tests.resources)

the kivakit-internal project could be useful to hide other things people shouldn't be using.

we could tweak the names here, but what do you think of the idea?

   Jon

**Comment by timboudreau** [comment]
Generally works, although `UnitTest` in a public project subclassing `CoreUnitTest` in a private project feels a little weird:

```
kivakit/
  kivakit-test/     UnitTest <------
  kivakit-internal/                |
    test/ contains CoreUnitTest ----
    unit-tests/
      core/ 
      resources/ 
```

**Comment by timboudreau** [comment]
Okay, I've updated the PR to structure things as described above.

**Pull request merged**
